### ISSUE TITLE
Commercial Recommendation

### ISSUE THREAD

**Issue by Nimtaa** [taivop/awesome-data-annotation#6]
Thanks for the list!
I think Scale AI (https://scale.com/) can be added to the commercial section.

**Comment by aliechoes** [comment]
as well as this
https://www.superannotate.com

**Comment by jenniferlin15** [comment]
My favorites of the commercial set is: https://www.lighttag.io/

**Comment by taivop** [comment]
Thank you for the recommendations! Added SuperAnnotate and LightTag in 389228f5fe92406a2eb50c44b310f36de66f4af7

I did not add Scale because they are technically not a tool: AFAIK you cannot use their tool without also purchasing their labelling service.
